parameters:
#    carnet_user.example.class: Carnet\UserBundle\Example

services:
#    carnet_user.example:
#        class: %carnet_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
